/**
 * project REST API
 * Specification of REST API for Project
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ListOfExtendedUsers } from './listOfExtendedUsers';

export interface CounselUsersByType { 
    as_admin: ListOfExtendedUsers;
    as_doctor: ListOfExtendedUsers;
    as_patient: ListOfExtendedUsers;
}