/**
 * project REST API
 * Specification of REST API for Project
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CovidMapDataTotalStats } from './covidMapDataTotalStats';

export interface CovidMapData { 
    updated_at: Date;
    /**
     * serialized GeoJSON FeatureCollection
     */
    data: string;
    total_stats: CovidMapDataTotalStats;
}