/**
 * project REST API
 * Specification of REST API for Project
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Location } from './location';

export interface GeneralProfileData { 
    email?: string;
    verified_email?: string;
    phone_number?: string;
    location?: Location;
    about?: string;
    zip_code?: string;
}