/**
 * project REST API
 * Specification of REST API for Project
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Suffixes } from './suffixes';

export interface IndividualUpdateRequest { 
    alias: string;
    gender?: string;
    date_of_birth?: string;
    first_name?: string;
    last_name?: string;
    middle_name?: string;
    mothers_maiden_name?: string;
    suffix?: Suffixes;
    language?: Array<string>;
}