/**
 * project REST API
 * Specification of REST API for Project
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coords } from './coords';
import { Country } from './country';

export interface Location { 
    country: Country;
    region?: string;
    subregion?: string;
    province?: string;
    city: string;
    street?: string;
    center: Coords;
}