/**
 * project REST API
 * Specification of REST API for Project
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BasicUsersAsList } from './basicUsersAsList';
import { Disease } from './disease';
import { Location } from './location';
import { OrganizationLink } from './organizationLink';
import { ProjectCommunity } from './projectCommunity';
import { ProjectPermissions } from './projectPermissions';
import { Specialty } from './specialty';
import { UserBasic } from './userBasic';
import { UserRelationToGroup } from './userRelationToGroup';
import { ValidityPeriod } from './validityPeriod';
import { VerificationStatus } from './verificationStatus';

export interface Project { 
    entity_id: string;
    permissions: ProjectPermissions;
    title: string;
    description: string;
    website?: string;
    type: string;
    diseases: Array<Disease>;
    funding_source?: string;
    specialities: Array<Specialty>;
    linked_organizations: Array<OrganizationLink>;
    location: Location;
    community?: ProjectCommunity;
    creator: UserBasic;
    validity_period: ValidityPeriod;
    verification_status: VerificationStatus;
    verification_message?: string;
    linked_projects?: Array<Project>;
    linked_projects_members?: BasicUsersAsList;
    actor_role: UserRelationToGroup;
}