/**
 * project REST API
 * Specification of REST API for Project
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProjectForVerification } from './projectForVerification';
import { UserBasic } from './userBasic';

export interface ProjectRequest { 
    entity_id: string;
    created_date: Date;
    request_state: ProjectRequest.RequestStateEnum;
    project: ProjectForVerification;
    assigned_to?: Array<UserBasic>;
    responded_date?: Date;
    responder?: UserBasic;
}
export namespace ProjectRequest {
    export type RequestStateEnum = 'New' | 'Assigned' | 'Responded';
    export const RequestStateEnum = {
        New: 'New' as RequestStateEnum,
        Assigned: 'Assigned' as RequestStateEnum,
        Responded: 'Responded' as RequestStateEnum
    };
}