/**
 * project REST API
 * Specification of REST API for Project
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateCommentRequest } from './createCommentRequest';

export interface ReplyCommentRequest extends CreateCommentRequest { 
    replied_comment_id?: string;
}