/**
 * project REST API
 * Specification of REST API for Project
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * По этому URL можно узнать suggested_values по одной букве. Не может быть одновременно с suggested_values.
 */
export interface SearchAttributeSuggestedQueryUrl { 
    href: string;
    method: string;
}