/**
 * project REST API
 * Specification of REST API for Project
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OneOfAny } from './oneOfAny';
import { Operator } from './operator';
import { SearchAttributeSuggestedQueryUrl } from './searchAttributeSuggestedQueryUrl';

export interface SearchAttribute { 
    /**
     * Visible name & identifier.
     */
    name: string;
    type: SearchAttribute.TypeEnum;
    /**
     * Visible names of operators & identifiers.
     */
    operators: Array<Operator>;
    suggested_query_url?: SearchAttributeSuggestedQueryUrl;
    /**
     * Список suggested elements. Должны интерпретироваться в зависимости от type. Не может быть одновременно с suggested_query_url.
     */
    suggested_values?: Array<OneOfAny>;
    default_selection?: OneOfAny;
}
export namespace SearchAttribute {
    export type TypeEnum = 'string' | 'geo' | 'number';
    export const TypeEnum = {
        String: 'string' as TypeEnum,
        Geo: 'geo' as TypeEnum,
        Number: 'number' as TypeEnum
    };
}