/**
 * project REST API
 * Specification of REST API for Project
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SecurityDescriptor { 
    user_id: string;
    permission: SecurityDescriptor.PermissionEnum;
}
export namespace SecurityDescriptor {
    export type PermissionEnum = 'owner' | 'reader' | 'writer';
    export const PermissionEnum = {
        Owner: 'owner' as PermissionEnum,
        Reader: 'reader' as PermissionEnum,
        Writer: 'writer' as PermissionEnum
    };
}