/**
 * project REST API
 * Specification of REST API for Project
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserBasic { 
    user_id: string;
    /**
     * individual alias or organization name
     */
    displayed_name: string;
    is_admin: boolean;
    deleted: boolean;
    image_url?: string;
    /**
     * channel_external_id if already exists
     */
    chat?: string;
}